meta_product_name: 'Teqis'
meta_title: 'Teqis - Enregistre, analyse et compare tes résultats en un instant'
meta_description: 'Teqis est le site dont tu as toujours rêvé afin de rapidement pouvoir enregistrer tes matchs, consulter tes statistiques détaillées et te comparer aux autre joueurs.'
meta_image: 'og_img_teqis.png'